[package]
name = "filament-e2ee"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = []
livekit-media = ["dep:libwebrtc"]
sqlcipher-store = ["dep:rusqlite"]

[lints]
workspace = true

[dependencies]
filament-core = { path = "../filament-core", version = "0.1.0" }
filament-protocol = { path = "../filament-protocol", version = "0.1.0" }
openmls = "0.8.1"
openmls_rust_crypto = "0.5.1"
openmls_basic_credential = "0.5.0"
openmls_traits = "0.5.0"
zeroize = "1"
thiserror = "2"
ed25519-dalek = { version = "2", features = ["rand_core", "zeroize"] }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
infer = "0.19"
libwebrtc = { version = "=0.3.42", optional = true }
base64 = "0.22"
argon2 = "0.5"
tantivy = "0.25"
tls_codec = "0.5"
ulid = "1"
rusqlite = { version = "=0.39.0", optional = true, default-features = false, features = ["bundled-sqlcipher-vendored-openssl", "limits"] }

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
