[package]
name = "filament-e2ee"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
filament-core = { path = "../filament-core", version = "0.1.0" }
openmls = "0.8.1"
openmls_rust_crypto = "0.5.1"
openmls_basic_credential = "0.5.0"
zeroize = "1"
thiserror = "2"
ed25519-dalek = { version = "2", features = ["rand_core", "zeroize"] }
rand = "0.8"
sha2 = "0.10"
tls_codec = "0.4.2"
